second commit
egor200201/golanghomework pull request #1
Opened 2021-07-07 14:37 UTC by egor200201

homework1

2021-07-09 11:41 UTC, nikonok requested changes
That works, but you need to change something:

- [x] Rename repository, you need to have one rep for all tasks. Not the new one for each
- [ ] Also rename your pull request (name should be correlate with task number)
- [ ] You can print "Hello world" string with emoji lib (like on 11 line). It will be more simplified
- [ ] And I suggest to remove file named "go" at the root of repo, but place file named README.md here (google for more about README.md)

2021-07-09 21:32 UTC, denislituev requested changes

2021-07-09 21:32 UTC, denislituev commented on package main.go
> +)
this could be one line, as one package imported. smth. like: **import "github.com/kyokomi/emoji"**

2021-07-10 16:09 UTC, denislituev approved these changes

2021-07-12 07:34 UTC, nikonok requested changes
Last cosmetic changes: rename file from `package main.go` into main.go and place it to folder task1 or something like that. Because it looks like a mess.

2021-07-15 09:31 UTC, nikonok approved these changes

2021-07-15 13:12 UTC, merged