homework2
egor200201/golanghomework pull request #2
Opened 2021-07-11 13:51 UTC by egor200201

2021-07-12 08:44 UTC, nikonok requested changes
- [x] Please rename module, because the most common used name is name of your GitHub repo (not knocker, use github.com/egor200201/golanghomework instead)
- [x] Remove bin file (*.exe) from git
- [x] Also you already have task1 and task2 files at master branch, you should commit into master only via pull requests
- [x] And I don't see fibfunction at changes in PR

2021-07-14 12:53 UTC, egor200201 commented
i dont understand why this brunch has conflicts.

2021-07-15 09:32 UTC, nikonok approved these changes

2021-07-15 20:22 UTC, denislituev approved these changes

2021-07-18 10:16 UTC, merged