Homework3
egor200201/golanghomework pull request #3
Opened 2021-07-18 11:57 UTC by egor200201

2021-07-19 10:00 UTC, nikonok requested changes
Please, add some more information output to your tasks. Not only "result".
And here also `package main.go` file in the branch, idk why it not shown at the diff. Maybe you need to update branch before merging
![image](https://user-images.githubusercontent.com/25906829/126142623-ecfaf5d2-ac68-4c9d-9d02-74ae8fec311c.png)

Maybe that will help you https://stackoverflow.com/questions/23748973/is-it-neccessary-to-update-git-branch-before-merging-it-to-develop-master

2021-07-19 10:00 UTC, nikonok commented on task3/avarage/avarege.go
> +func Average(a [6]int) float64 {
Please rename file, because it name contains error (compare with function name)

2021-07-19 10:00 UTC, nikonok commented on task3/mapbykeys/map.go
> +
Remove new line from start at all functions.

2021-07-19 10:00 UTC, nikonok commented on task3/reverse/reverse.go
> +func main() {
Move it to function according to HW task instructions.

2021-07-22 07:22 UTC, denislituev approved these changes

2021-08-06 10:48 UTC, nikonok approved these changes

2021-08-07 15:01 UTC, merged