Homework6
egor200201/golanghomework pull request #6
Opened 2021-08-04 15:45 UTC by egor200201

2021-08-04 18:03 UTC, denislituev requested changes
Why the first commit with tests is presented in this PR? It related to another task.

2021-08-04 18:03 UTC, denislituev commented on task6/part1.go
> +	const port = 8080
as usual we declare such consts as global, out of main() function

2021-08-04 18:03 UTC, denislituev commented on task6/part2/client/client.go
> +		fmt.Printf("Sending message: %s; to port: %d\n", message[:len(message)-1], port)
this string messages on the line 31 and line 54 we also could declare as consts, to avoid mess in the code and increase readability

2021-08-04 18:03 UTC, denislituev commented on task6/part2/server/server.go
> +	const port = 8081
move out from main()

2021-08-04 18:03 UTC, denislituev commented on task6/part3/server/server.go
> +	const port = 8080
move it out from main()

2021-08-06 10:50 UTC, nikonok requested changes

2021-08-06 10:50 UTC, nikonok commented on task6/part1.go
> +		Header: Header{
You forget about about other headers that can be passed.
The HW task did not say that only this headers were needed =)
https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
Example:
`curl "http://127.0.0.1:8081/headers" -H "Max-Forwards: 10"` should return:
```json
{
  "Host": "127.0.0.1:8080",
  "UserAgent": "curl/7.68.0",
  "RequestURI": "/headers",
  "Header": {
    "Accept": [
      "*/*"
    ],
    "Max-Forwards": [
      "10"
    ],
    "User-Agent": [
      "curl/7.68.0"
    ]
  }
}
```

2021-08-10 07:05 UTC, denislituev approved these changes

2021-08-13 15:28 UTC, nikonok approved these changes

2021-08-13 15:43 UTC, merged